parameters:
    sidus.filter.advanced_text_choices:
        'sidus.filter.combo._like_': '_like_'
        'sidus.filter.combo.exact': 'exact'
        'sidus.filter.combo.like_': 'like_'
        'sidus.filter.combo._like': '_like'
        'sidus.filter.combo.notlike_': 'notlike_'
        'sidus.filter.combo._notlike': '_notlike'
        'sidus.filter.combo._notlike_': '_notlike_'
        'sidus.filter.combo.empty': 'empty'
        'sidus.filter.combo.notempty': 'notempty'
        'sidus.filter.combo.null': 'null'
        'sidus.filter.combo.notnull': 'notnull'

    sidus.filter.advanced_number_choices:
        'sidus.filter.combo.exact': 'exact'
        'sidus.filter.combo.greaterthan': 'greaterthan'
        'sidus.filter.combo.lowerthan': 'lowerthan'
        'sidus.filter.combo.greaterthanequals': 'greaterthanequals'
        'sidus.filter.combo.lowerthanequals': 'lowerthanequals'
        'sidus.filter.combo.empty': 'empty'
        'sidus.filter.combo.notempty': 'notempty'
        'sidus.filter.combo.null': 'null'
        'sidus.filter.combo.notnull': 'notnull'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Sidus\FilterBundle\Doctrine\:
        resource: '../../Doctrine/'

    Sidus\FilterBundle\Doctrine\Filter\Type\DateRangeFilterType:
        arguments:
            - date_range
            - 'Sidus\FilterBundle\Form\Type\DateRangeType'

    Sidus\FilterBundle\Doctrine\Filter\Type\TextFilterType:
        arguments:
            - text
            - 'Symfony\Component\Form\Extension\Core\Type\TextType'

    Sidus\FilterBundle\Doctrine\Filter\Type\CustomChoiceFilterType:
        arguments:
            - custom_choice
            - 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'

    Sidus\FilterBundle\Doctrine\Filter\Type\ChoiceFilterType:
        arguments:
            - choice
            - 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'

    Sidus\FilterBundle\Doctrine\Filter\Type\EntityFilterType:
        arguments:
            - entity
            - Symfony\Bridge\Doctrine\Form\Type\EntityType

    Sidus\FilterBundle\Doctrine\Filter\Type\ExactFilterType:
        arguments:
            - exact
            - 'Symfony\Component\Form\Extension\Core\Type\TextType'

    Sidus\FilterBundle\Doctrine\Filter\Type\AdvancedTextFilterType:
        arguments:
            - advanced_text
            - Sidus\FilterBundle\Form\Type\ComboFilterType
            -   input_type: Symfony\Component\Form\Extension\Core\Type\TextType
                options_choices: '%sidus.filter.advanced_text_choices%'

    Sidus\FilterBundle\Doctrine\Filter\Type\AdvancedNumberFilterType:
        arguments:
            - advanced_number
            - Sidus\FilterBundle\Form\Type\ComboFilterType
            -   input_type: Symfony\Component\Form\Extension\Core\Type\TextType
                options_choices: '%sidus.filter.advanced_number_choices%'

    Sidus\FilterBundle\Doctrine\Filter\Type\NotNullFilterType:
        arguments:
            - not_null
            - Symfony\Component\Form\Extension\Core\Type\CheckboxType
